### ISSUE TITLE
Data Table

### ISSUE THREAD

**Issue by NagWolf** [mcphee11/genesys-cloud-messaging-survey#1]
Hi 

Can you please explain the data table entries and examples of the values that need to be populated or does the flow populate them?

**Comment by mcphee11** [comment]
@NagWolf it really depends on what you want to show in the UI for the customer. This example is built on the ability to show both the "Transcript" & "Survey" as buttons at the end of the session. So for that you need a "KEY" which is the conversationId,  the transcriptUrl as well as the surveyUrl as additional columns. This is so that the Buttons in the popup can link out to these locations, info in is the readMe here: https://github.com/mcphee11/genesys-cloud-messaging-survey?tab=readme-ov-file#step-4---create-datatable if you also wanted to show additional buttons of options then you may want to have additional columns for more info. Its really the survey that causes this level of complexity due to the way the policy runs today. If you only wanted the transcript i would do it a different way to make life simplier. Remember this is designed as an example and you can make it into your own through the APIs. Any more quesitons let me know.

Cheers.
